---
# this should go in the LOCAL profile
# Should access at: http://localhost:8080/h2/
spring:
  config:
    activate:
      on-profile: test, default
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
